---
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres1
    environment:
      POSTGRES_USER: rehearse
      POSTGRES_PASSWORD: rehearse
      POSTGRES_DB: rehearse
    ports:
      - '5438:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
